# Generated by Django 3.1.4 on 2021-01-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('mbid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('song_count', models.IntegerField()),
                ('average_word_length', models.FloatField()),
            ],
        ),
    ]
